### ISSUE TITLE
Set jupytext.formats with the jupytext commands

### ISSUE THREAD

**Issue by mwouts** [mwouts/jupyterlab-jupytext#1]
This has to be implemented [here](https://github.com/mwouts/jupyterlab-jupytext/blob/4d4fdde36ab3a971a8910261cc6937c91261c3e7/src/index.ts#L54-L56).

**Comment by FlorianWetschoreck** [comment]
Hi Marc, maybe this thread helps you?
https://github.com/jupyterlab/jupyterlab/issues/3379

**Comment by mwouts** [comment]
Hi Florian, thanks for the reference, which looks promising! I will give it a try soon.
