### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by jamesmyatt** [mwouts/jupyterlab-jupytext#2]
Is this repo dead? Looks like it's been moved to https://github.com/mwouts/jupytext/tree/master/packages/labextension

**Comment by mwouts** [comment]
Hi @jamesmyatt , that's right, the extension is now being developed in the Jupytext repo itself. I'll mark this repo as "archived", and provide a link to the main repo.

**Comment by jamesmyatt** [comment]
Great 👍

**Comment by jamesmyatt** [comment]
I'll leave this issue open until you've archived the project.
