### ISSUE TITLE
Separate jupyterlab-jupytext from jupytext (+ include the commit history)

### ISSUE THREAD

**Issue by mwouts** [mwouts/jupyterlab-jupytext#6]
In order to 
- support both JupyterLab 3 and JupyterLab 4, and 
- follow the recommended pattern that JupyterLab extensions should be pip/conda packages, 

we should move back the [`packages/labextension`](https://github.com/mwouts/jupytext/tree/main/packages/labextension) folder of `jupytext` to this repository.

Tasks
- [ ] Extract the folder history and create a PR on this repository
- [ ] Prepare a release candidate `jupyterlab-jupytext==1.3.9rc0` (or `3.0.0rc0` ?) and publish it on pip/conda
- [ ] Rebase the branch `jupyterlab4` on the RC, prepare a release candidate `jupyterlab-jupytext==1.4.0rc0` (or `4.0.0rc0`?) and publish it on pip/conda
- [ ] Fix the conda packaging of `jupytext==1.14.6`
- [ ] Prepare a release candidate of `jupytext==1.15.0.rc0` without the lab extension, but with a dependency on `jupyterlab-jupytext`

Advice are welcome!

**Comment by parmentelat** [comment]
can you please elaborate on the reasons for `jupytext` to depend on `jupyterlab-jupytext` ?

this in contrary to intuition; one can easily foresee contexts where you need jupytext as a command-line only tool for translating between text formats, and in such contexts having to install jupyterlab looks quite overwhelming...

---
also, what is the plan to deal with the jlab3/jlab4 coexistence ? 
did I interpret correctly that you plan on having each in a separate folder of the current repo ?
or do you plan on maintaining primarily the jlab4 extension in a single folder (with a maintenance branch for the case where jlab3 would require a new release as well) ?

I guess most jlab extensions will face the same decisions when it comes to managing several jlab versions, does the community have best practices here ?

**Comment by parmentelat** [comment]
on the versioning scheme, I agree that having the jlab3 extension numbered 3.x and the jlab4 extension numbered 4.x is about right

**Comment by mwouts** [comment]
We have decided to continue to ship the extension with the main `jupytext` package.
